HOST_URL = "C:/windows/System32/drivers/etc/hosts"
HOST_COPY = "./host_copy"
HOST_BACKUP = "./host_backup"
PADRAO_URL1 = "http://"
PADRAO_URL2 = "https://"
PADRAO_INPUT = "www[.]([\w]?)+[.]com[.]?([\w]?)+" #www.{any}.com{.any}{any} #www.google.com #www.google.com.br
LOCAL_IP = "127.0.0.1"
DESCRIPT_START_INDEX = 52
BLANK_SPACE_IP = 6
BLANK_SPACE_DESC = 10
BR_URL = ".br"